export const SERBIAN_CITIES_CEMETEREIS = [
  {
    name: 'Novo Groblje',
    address: 'Ruzveltova 50',
    city: 'Beograd',
    location: { x: 20.4825, y: 44.8186 },
  },
  {
    name: 'Topčidersko Groblje',
    address: 'Knez Miloša 35',
    city: 'Beograd',
    location: { x: 20.4542, y: 44.7911 },
  },
  {
    name: 'Lešće',
    address: 'Patrijarha Dimitrija 34',
    city: 'Beograd',
    location: { x: 20.5414, y: 44.8229 },
  },
  {
    name: 'Centralno Groblje',
    address: 'Višnjička 9',
    city: 'Beograd',
    location: { x: 20.5065, y: 44.8159 },
  },
  {
    name: 'Banjica Groblje',
    address: 'Banjica bb',
    city: 'Beograd',
    location: { x: 20.4721, y: 44.7603 },
  },
  {
    name: 'Orlovača',
    address: 'Ibarski put bb',
    city: 'Beograd',
    location: { x: 20.3817, y: 44.7231 },
  },
  {
    name: 'Bežanijsko Groblje',
    address: 'Jurija Gagarina 335',
    city: 'Beograd',
    location: { x: 20.3844, y: 44.8134 },
  },
  {
    name: 'Zemun Groblje',
    address: 'Zemunska 40',
    city: 'Beograd',
    location: { x: 20.4104, y: 44.8471 },
  },
  {
    name: 'Groblje Nova Bežanija',
    address: 'Omladinskih brigada 35',
    city: 'Beograd',
    location: { x: 20.3851, y: 44.8111 },
  },
  {
    name: 'Groblje Kotež',
    address: 'Slanački put bb',
    city: 'Beograd',
    location: { x: 20.5331, y: 44.8452 },
  },

  {
    name: 'Almaško Groblje',
    address: 'Almaška 35',
    city: 'Novi Sad',
    location: { x: 19.8369, y: 45.2553 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Futoški put 48',
    city: 'Novi Sad',
    location: { x: 19.8248, y: 45.2601 },
  },
  {
    name: 'Jevrejsko Groblje',
    address: 'Jevrejska 12',
    city: 'Novi Sad',
    location: { x: 19.8439, y: 45.2557 },
  },
  {
    name: 'Novo Groblje',
    address: 'Preradovićeva 4',
    city: 'Novi Sad',
    location: { x: 19.8397, y: 45.2532 },
  },
  {
    name: 'Petrovaradinsko Groblje',
    address: 'Reljkovićeva 2',
    city: 'Novi Sad',
    location: { x: 19.8798, y: 45.2459 },
  },
  {
    name: 'Futroško Groblje',
    address: 'Futoška 10',
    city: 'Novi Sad',
    location: { x: 19.8311, y: 45.2506 },
  },
  {
    name: 'Groblje Veternik',
    address: 'Vojvode Mišića bb',
    city: 'Novi Sad',
    location: { x: 19.8172, y: 45.2545 },
  },
  {
    name: 'Sremska Kamenica Groblje',
    address: 'Patrijarha Rajačića 1',
    city: 'Sremska Kamenica',
    location: { x: 19.8531, y: 45.2236 },
  },
  {
    name: 'Novo Groblje',
    address: 'Bulevar Svetog cara Konstantina 80',
    city: 'Niš',
    location: { x: 21.9024, y: 43.3235 },
  },
  {
    name: 'Vojničko Groblje',
    address: 'Ratnih vojvoda 1',
    city: 'Niš',
    location: { x: 21.9152, y: 43.3148 },
  },
  {
    name: 'Groblje Palilula',
    address: 'Knjaževačka 144',
    city: 'Niš',
    location: { x: 21.9145, y: 43.3183 },
  },
  {
    name: 'Donje Međurovo Groblje',
    address: 'Donje Međurovo bb',
    city: 'Niš',
    location: { x: 21.8824, y: 43.2891 },
  },
  {
    name: 'Groblje Brzi Brod',
    address: 'Brzi Brod bb',
    city: 'Niš',
    location: { x: 21.9315, y: 43.3067 },
  },
  {
    name: 'Groblje Pantelej',
    address: 'Zetska 8',
    city: 'Niš',
    location: { x: 21.9304, y: 43.3337 },
  },

  {
    name: 'Gradsko Groblje',
    address: 'Miloja Pavlovića 23',
    city: 'Kragujevac',
    location: { x: 20.9263, y: 44.0141 },
  },
  {
    name: 'Šumarice Groblje',
    address: 'Šumarice bb',
    city: 'Kragujevac',
    location: { x: 20.8783, y: 44.0161 },
  },
  {
    name: 'Vojničko Groblje',
    address: 'Vojvode Putnika 43',
    city: 'Kragujevac',
    location: { x: 20.9228, y: 44.0105 },
  },
  {
    name: 'Groblje Ilićevo',
    address: 'Ilićevo bb',
    city: 'Kragujevac',
    location: { x: 20.8971, y: 44.0083 },
  },
  {
    name: 'Groblje Pivara',
    address: 'Pivarska bb',
    city: 'Kragujevac',
    location: { x: 20.9159, y: 44.0023 },
  },
  {
    name: 'Groblje Bajski Put',
    address: 'Bajski put bb',
    city: 'Subotica',
    location: { x: 19.6542, y: 46.1042 },
  },
  {
    name: 'Groblje Aleksandrovo',
    address: 'Aleksandrovo bb',
    city: 'Subotica',
    location: { x: 19.6581, y: 46.1005 },
  },
  {
    name: 'Groblje Kelebija',
    address: 'Kelebija bb',
    city: 'Subotica',
    location: { x: 19.6336, y: 46.1157 },
  },
  {
    name: 'Groblje Tavankut',
    address: 'Tavankut bb',
    city: 'Subotica',
    location: { x: 19.5962, y: 46.1484 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Beogradski put bb',
    city: 'Subotica',
    location: { x: 19.6618, y: 46.1022 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Senćanski put bb',
    city: 'Subotica',
    location: { x: 19.6587, y: 46.1029 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Beogradska bb',
    city: 'Zrenjanin',
    location: { x: 20.3904, y: 45.3836 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Cara Dušana bb',
    city: 'Zrenjanin',
    location: { x: 20.3995, y: 45.3797 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Save Tekelije bb',
    city: 'Zrenjanin',
    location: { x: 20.4083, y: 45.3814 },
  },
  {
    name: 'Groblje Mužlja',
    address: 'Mužlja bb',
    city: 'Zrenjanin',
    location: { x: 20.385, y: 45.3742 },
  },
  {
    name: 'Groblje Bagljaš',
    address: 'Bagljaš bb',
    city: 'Zrenjanin',
    location: { x: 20.4018, y: 45.376 },
  },
  {
    name: 'Novo Groblje',
    address: 'Hajduk Veljkova 2',
    city: 'Pančevo',
    location: { x: 20.6505, y: 44.8718 },
  },
  {
    name: 'Staro Groblje',
    address: 'Josifa Marinkovića bb',
    city: 'Pančevo',
    location: { x: 20.6569, y: 44.8729 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Miloša Obilića bb',
    city: 'Pančevo',
    location: { x: 20.6521, y: 44.8712 },
  },
  {
    name: 'Groblje Glogonjski Rit',
    address: 'Glogonjski Rit bb',
    city: 'Pančevo',
    location: { x: 20.6791, y: 44.8635 },
  },
  {
    name: 'Groblje Vojlovica',
    address: 'Vojlovica bb',
    city: 'Pančevo',
    location: { x: 20.6703, y: 44.8532 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Bulevar Oslobođenja 10',
    city: 'Čačak',
    location: { x: 20.3534, y: 43.8914 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Nemanjina bb',
    city: 'Čačak',
    location: { x: 20.3475, y: 43.892 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Svetog Save bb',
    city: 'Čačak',
    location: { x: 20.3437, y: 43.8902 },
  },
  {
    name: 'Groblje Konjevići',
    address: 'Konjevići bb',
    city: 'Čačak',
    location: { x: 20.3456, y: 43.8957 },
  },
  {
    name: 'Groblje Ljubić',
    address: 'Ljubić bb',
    city: 'Čačak',
    location: { x: 20.3412, y: 43.8991 },
  },

  {
    name: 'Gradsko Groblje',
    address: 'Dragoslava Srejovića 1',
    city: 'Kraljevo',
    location: { x: 20.6894, y: 43.7254 },
  },
  {
    name: 'Novo Groblje',
    address: 'Žička bb',
    city: 'Kraljevo',
    location: { x: 20.6925, y: 43.7281 },
  },
  {
    name: 'Vojničko Groblje',
    address: 'Karađorđeva bb',
    city: 'Kraljevo',
    location: { x: 20.6883, y: 43.7235 },
  },
  {
    name: 'Groblje Ribnica',
    address: 'Ribnica bb',
    city: 'Kraljevo',
    location: { x: 20.6872, y: 43.7295 },
  },
  {
    name: 'Groblje Adrani',
    address: 'Adrani bb',
    city: 'Kraljevo',
    location: { x: 20.6748, y: 43.7181 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Karađorđeva bb',
    city: 'Smederevo',
    location: { x: 20.9517, y: 44.6648 },
  },
  {
    name: 'Novo Groblje',
    address: 'Miloša Velikog bb',
    city: 'Smederevo',
    location: { x: 20.9534, y: 44.6645 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Dunavska bb',
    city: 'Smederevo',
    location: { x: 20.9562, y: 44.6673 },
  },
  {
    name: 'Groblje Vranovo',
    address: 'Vranovo bb',
    city: 'Smederevo',
    location: { x: 20.9675, y: 44.671 },
  },
  {
    name: 'Groblje Lugavčina',
    address: 'Lugavčina bb',
    city: 'Smederevo',
    location: { x: 21.0004, y: 44.6821 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Bulevar Oslobođenja bb',
    city: 'Leskovac',
    location: { x: 21.9476, y: 42.9984 },
  },
  {
    name: 'Špitaljsko Groblje',
    address: 'Špitaljski put bb',
    city: 'Leskovac',
    location: { x: 21.9453, y: 42.9975 },
  },
  {
    name: 'Novo Groblje',
    address: 'Svetozara Markovića bb',
    city: 'Leskovac',
    location: { x: 21.9447, y: 42.9993 },
  },
  {
    name: 'Groblje Bobište',
    address: 'Bobište bb',
    city: 'Leskovac',
    location: { x: 21.9468, y: 42.9956 },
  },
  {
    name: 'Groblje Donje Sinkovce',
    address: 'Donje Sinkovce bb',
    city: 'Leskovac',
    location: { x: 21.9369, y: 43.0043 },
  },

  {
    name: 'Pravoslavno Groblje Lazarica',
    address: 'Lazarica bb',
    city: 'Kruševac',
    location: { x: 21.3265, y: 43.5806 },
  },
  {
    name: 'Groblje Veliki Šiljegovac',
    address: 'Veliki Šiljegovac bb',
    city: 'Kruševac',
    location: { x: 21.2624, y: 43.5421 },
  },

  {
    name: 'Gradsko Groblje Dovarje',
    address: 'Dovarje bb',
    city: 'Užice',
    location: { x: 19.8494, y: 43.8539 },
  },
  {
    name: 'Novo Groblje',
    address: 'Kralja Petra I bb',
    city: 'Užice',
    location: { x: 19.849, y: 43.853 },
  },
  {
    name: 'Groblje Carina',
    address: 'Carina bb',
    city: 'Užice',
    location: { x: 19.8517, y: 43.8523 },
  },
  {
    name: 'Pravoslavno Groblje Sevojno',
    address: 'Sevojno bb',
    city: 'Užice',
    location: { x: 19.7896, y: 43.8495 },
  },
  {
    name: 'Groblje Krčagovo',
    address: 'Krčagovo bb',
    city: 'Užice',
    location: { x: 19.8395, y: 43.8541 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Partizanski put bb',
    city: 'Vranje',
    location: { x: 21.9012, y: 42.5487 },
  },
  {
    name: 'Novo Groblje',
    address: 'Svetosavska bb',
    city: 'Vranje',
    location: { x: 21.9036, y: 42.55 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Bore Stankovića bb',
    city: 'Vranje',
    location: { x: 21.8987, y: 42.5493 },
  },
  {
    name: 'Groblje Sobina',
    address: 'Sobina bb',
    city: 'Vranje',
    location: { x: 21.8972, y: 42.5522 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Zmaj Jovina bb',
    city: 'Vranje',
    location: { x: 21.9042, y: 42.5513 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Janka Veselinovića bb',
    city: 'Šabac',
    location: { x: 19.6893, y: 44.7567 },
  },
  {
    name: 'Novo Groblje',
    address: 'Svetog Save bb',
    city: 'Šabac',
    location: { x: 19.6902, y: 44.7556 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Vojvode Mišića bb',
    city: 'Šabac',
    location: { x: 19.6927, y: 44.7549 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Karađorđeva bb',
    city: 'Šabac',
    location: { x: 19.6873, y: 44.7571 },
  },
  {
    name: 'Groblje Majur',
    address: 'Majur bb',
    city: 'Šabac',
    location: { x: 19.682, y: 44.7541 },
  },

  {
    name: 'Veliko Pravoslavno Groblje',
    address: 'Venac Radomira Putnika bb',
    city: 'Sombor',
    location: { x: 19.0949, y: 45.7756 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Jovana Dučića bb',
    city: 'Sombor',
    location: { x: 19.0974, y: 45.7752 },
  },
  {
    name: 'Jevrejsko Groblje',
    address: 'Vojvođanska bb',
    city: 'Sombor',
    location: { x: 19.0925, y: 45.775 },
  },
  {
    name: 'Groblje Čonoplja',
    address: 'Čonoplja bb',
    city: 'Sombor',
    location: { x: 19.0117, y: 45.8446 },
  },
  {
    name: 'Groblje Kljajićevo',
    address: 'Kljajićevo bb',
    city: 'Sombor',
    location: { x: 19.0985, y: 45.8612 },
  },
  {
    name: 'Novo Groblje',
    address: 'Vojvode Mišića bb',
    city: 'Valjevo',
    location: { x: 19.8921, y: 44.2742 },
  },
  {
    name: 'Staro Groblje',
    address: 'Sinđelićeva bb',
    city: 'Valjevo',
    location: { x: 19.8944, y: 44.2748 },
  },
  {
    name: 'Pravoslavno Groblje Brđani',
    address: 'Brđani bb',
    city: 'Valjevo',
    location: { x: 19.8898, y: 44.2767 },
  },
  {
    name: 'Groblje Petnica',
    address: 'Petnica bb',
    city: 'Valjevo',
    location: { x: 19.8947, y: 44.2785 },
  },
  {
    name: 'Groblje Divci',
    address: 'Divci bb',
    city: 'Valjevo',
    location: { x: 19.8821, y: 44.2733 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Kneza Miloša bb',
    city: 'Požarevac',
    location: { x: 21.1927, y: 44.6222 },
  },
  {
    name: 'Novo Groblje',
    address: 'Božidarčeva bb',
    city: 'Požarevac',
    location: { x: 21.1933, y: 44.6218 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Nemanjina bb',
    city: 'Požarevac',
    location: { x: 21.192, y: 44.6235 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Jovana Šerbanovića bb',
    city: 'Požarevac',
    location: { x: 21.1914, y: 44.6215 },
  },
  {
    name: 'Groblje Kostolac',
    address: 'Kostolac bb',
    city: 'Požarevac',
    location: { x: 21.1378, y: 44.7011 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Nikole Pašića 58',
    city: 'Zaječar',
    location: { x: 22.2985, y: 43.9063 },
  },
  {
    name: 'Novo Groblje',
    address: 'Karađorđeva bb',
    city: 'Zaječar',
    location: { x: 22.2972, y: 43.9072 },
  },
  {
    name: 'Groblje Kotlujevac',
    address: 'Kotlujevac bb',
    city: 'Zaječar',
    location: { x: 22.2959, y: 43.9078 },
  },
  {
    name: 'Groblje Veliki Izvor',
    address: 'Veliki Izvor bb',
    city: 'Zaječar',
    location: { x: 22.3021, y: 43.9101 },
  },
  {
    name: 'Groblje Grljan',
    address: 'Grljan bb',
    city: 'Zaječar',
    location: { x: 22.296, y: 43.912 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Fruškogorska bb',
    city: 'Sremska Mitrovica',
    location: { x: 19.6028, y: 44.9813 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Šaševačka bb',
    city: 'Sremska Mitrovica',
    location: { x: 19.5984, y: 44.9807 },
  },
  {
    name: 'Katoličko Groblje',
    address: 'Stari Šor bb',
    city: 'Sremska Mitrovica',
    location: { x: 19.605, y: 44.982 },
  },
  {
    name: 'Groblje Laćarak',
    address: 'Laćarak bb',
    city: 'Sremska Mitrovica',
    location: { x: 19.5981, y: 44.9842 },
  },
  {
    name: 'Groblje Mačvanska Mitrovica',
    address: 'Mačvanska Mitrovica bb',
    city: 'Sremska Mitrovica',
    location: { x: 19.6094, y: 44.9795 },
  },
  {
    name: 'Gradsko Groblje',
    address: 'Narodnog fronta bb',
    city: 'Loznica',
    location: { x: 19.2261, y: 44.5317 },
  },
  {
    name: 'Novo Groblje',
    address: 'Jovana Cvijića bb',
    city: 'Loznica',
    location: { x: 19.2293, y: 44.5296 },
  },
  {
    name: 'Pravoslavno Groblje',
    address: 'Aleksandra Rankovića bb',
    city: 'Loznica',
    location: { x: 19.2245, y: 44.5331 },
  },
  {
    name: 'Groblje Klupci',
    address: 'Klupci bb',
    city: 'Loznica',
    location: { x: 19.2258, y: 44.5353 },
  },
  {
    name: 'Groblje Lešnica',
    address: 'Lešnica bb',
    city: 'Loznica',
    location: { x: 19.2138, y: 44.5365 },
  },
];
